Importing all the libraries 

In [28]:
import open3d as o3d
import numpy as np
import importlib
#import matplotlib.pyplot as plt
#import h5py
import functions.pc_matching
import functions.mat_to_py
import functions.viz
import functions.pc_registration
importlib.reload(functions.pc_matching)
importlib.reload(functions.mat_to_py)
importlib.reload(functions.viz)
importlib.reload(functions.pc_registration)
from functions.pc_matching import PCMatch
from functions.mat_to_py import PCNIData
from functions.viz import pc_viz, video_cv, pc2video
from functions.pc_registration import PointReg

Initialising all the DataPoints

In [29]:
match_points = PCMatch()
data_points1 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=6)
data_points2 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=7)
data_points3 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=8)
data_points4 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=9)
datapoints = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=3)

In [30]:
data_list1 = data_points1('pc')
data_list2 = data_points2('pc')
data_list3 = data_points3('pc')
data_list4 = data_points4('pc')
data_lists = datapoints('pc')

loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_6_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_7_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_8_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_9_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_3_pc.mat


In [8]:
static_point = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=1)
static_pc = static_point('pc')
pc_viz(static_pc[150])
np.save('ref/reference_pc_new.npy',static_pc[120])

loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_1_pc.mat


Clustering and Tracking of Differenet Objects

In [82]:
import functions.ClusterFinders
importlib.reload(functions.ClusterFinders)
from functions.ClusterFinders import ClusterFinder
# static_pc = np.load('reference_pc_new.npy')
static_pc = np.load('ref/reference_pc_new.npy')
Find = ClusterFinder()
object,cluster = Find(static_pc,data_list3,24,30,2)

[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 4
point cloud has 4 clusters
[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 4
point cloud has 4 clusters
[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 4
point cloud has 4 clusters
the length of the cluster and the objects are 
1
1
throw
1
1
2
2
catch
throw
1
1
2
2
catch
throw
1
1
2
2
catch
throw
1
1
2
2
catch
the length of the cluster and the objects are 
2
2
throw
2
2
3
3
catch
throw
2
2
3
3
catch
throw
2
2
3
3
catch
throw
2
2
3
3
catch
the length of the cluster and the objects are 
3
3


Registration of Objects

In [83]:
import functions.pc_registration
importlib.reload(functions.pc_registration)
from functions.pc_registration import PointReg
reg_points = Find.registration(cluster,0)

Initial number of points in cluster:  166
wow
saved transformation
[[ 1.          0.          0.          0.03841829]
 [ 0.          1.          0.         -0.00330293]
 [ 0.          0.          1.         -0.01581407]
 [ 0.          0.          0.          1.        ]]
Apply Generalised ICP
RegistrationResult with fitness=9.945946e-01, inlier_rmse=2.698405e-02, and correspondence_set size of 184
Access transformation to get result.
Transformation after ICP is:
[[ 0.99969064  0.00345285  0.02463147 -0.02140752]
 [-0.00536038  0.99695439  0.07780241 -0.12401226]
 [-0.02428781 -0.07791038  0.99666447 -0.00869558]
 [ 0.          0.          0.          1.        ]]
184  points added
wow
saved transformation
[[ 0.99969064  0.00345285  0.02463147 -0.02140752]
 [-0.00536038  0.99695439  0.07780241 -0.12401226]
 [-0.02428781 -0.07791038  0.99666447 -0.00869558]
 [ 0.          0.          0.          1.        ]]
Apply Generalised ICP
RegistrationResult with fitness=9.898477e-01, inlier_rmse=

In [85]:
Find.registration(cluster,1)

Initial number of points in cluster:  151
wow
saved transformation
[[ 1.          0.          0.          0.02812123]
 [ 0.          1.          0.         -0.00413027]
 [ 0.          0.          1.         -0.01114273]
 [ 0.          0.          0.          1.        ]]
Apply Generalised ICP
RegistrationResult with fitness=9.554140e-01, inlier_rmse=2.681317e-02, and correspondence_set size of 150
Access transformation to get result.
Transformation after ICP is:
[[ 0.99831589  0.03769707 -0.04409444  0.10123104]
 [-0.04139013  0.99542797 -0.08608141  0.25785854]
 [ 0.04064782  0.08776151  0.99531185 -0.12977311]
 [ 0.          0.          0.          1.        ]]
150  points added
wow
saved transformation
[[ 0.99831589  0.03769707 -0.04409444  0.10123104]
 [-0.04139013  0.99542797 -0.08608141  0.25785854]
 [ 0.04064782  0.08776151  0.99531185 -0.12977311]
 [ 0.          0.          0.          1.        ]]
Apply Generalised ICP
RegistrationResult with fitness=8.518519e-01, inlier_rmse=

array([[2.73980546, 0.27495185, 1.88993025],
       [2.73882914, 0.28451386, 1.88993025],
       [2.73504519, 0.23595268, 1.88444734],
       ...,
       [2.64676136, 0.1369819 , 2.19473061],
       [2.63628465, 0.26806766, 2.21988592],
       [2.63333267, 0.28611   , 2.22232981]])

In [51]:
def display_inlier_outlier(cloud, ind):
    inlier_cloud = cloud.select_by_index(ind)
    outlier_cloud = cloud.select_by_index(ind, invert=True)

    print("Showing outliers (red) and inliers (gray): ")
    outlier_cloud.paint_uniform_color([0, 1, 0])
    inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
    o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud],
                                      zoom=0.3412,
                                      front=[0.4257, -0.2125, -0.8795],
                                      lookat=[2.6172, 2.0475, 1.532],
                                      up=[-0.0694, -0.9768, 0.2024])

In [47]:
len(reg_points)

1804