Importing all the libraries 

In [1]:
import open3d as o3d
import numpy as np
import importlib
#import matplotlib.pyplot as plt
#import h5py
import functions.pc_matching
import functions.mat_to_py
import functions.viz
import functions.pc_registration
importlib.reload(functions.pc_matching)
importlib.reload(functions.mat_to_py)
importlib.reload(functions.viz)
importlib.reload(functions.pc_registration)
from functions.pc_matching import PCMatch
from functions.mat_to_py import PCNIData
from functions.viz import pc_viz, video_cv, pc2video
from functions.pc_registration import PointReg

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Initialising all the DataPoints

In [3]:
match_points = PCMatch()
data_points1 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=6)
data_points2 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=7)
data_points3 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=8)
data_points4 = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=9)
datapoints = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=3)

In [5]:
data_list1 = data_points1('pc')
data_list2 = data_points2('pc')
data_list3 = data_points3('pc')
data_list4 = data_points4('pc')
data_lists = datapoints('pc')

loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_6_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_7_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_8_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_9_pc.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_3_pc.mat


Initialising the Static Reference Frame

In [8]:
static_point = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=1)
static_pc = static_point('pc')
pc_viz(static_pc[150])
np.save('ref/reference_pc_new.npy',static_pc[120])

loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_1_pc.mat


Clustering and Tracking of Differenet Objects

In [13]:
import functions.ClusterFinders
importlib.reload(functions.ClusterFinders)
from functions.ClusterFinders import ClusterFinder
# static_pc = np.load('reference_pc_new.npy')
static_pc = np.load('ref/reference_pc_new.npy')
Find = ClusterFinder()
object,cluster = Find(static_pc,data_list3,24,26,2)

[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 4
point cloud has 4 clusters
the length of the cluster and the objects are 
1
1


Registration of Objects

In [10]:
import functions.pc_registration
importlib.reload(functions.pc_registration)
from functions.pc_registration import PointReg
reg_points = Find.registration(cluster,1)

Initial number of points in cluster:  52
Apply Generalised ICP
RegistrationResult with fitness=1.000000e+00, inlier_rmse=0.000000e+00, and correspondence_set size of 52
Access transformation to get result.
Transformation after ICP is:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
0  points added
Apply Generalised ICP
RegistrationResult with fitness=1.000000e+00, inlier_rmse=1.446594e-02, and correspondence_set size of 52
Access transformation to get result.
Transformation after ICP is:
[[ 0.99394927  0.07516975 -0.08008966  0.22541532]
 [-0.080279    0.99480442 -0.06260554  0.20541082]
 [ 0.07496751  0.06865625  0.99481968 -0.01052782]
 [ 0.          0.          0.          1.        ]]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GL

In [13]:
Find.registration(cluster,0)

Initial number of points in cluster:  159
Apply Generalised ICP
RegistrationResult with fitness=1.000000e+00, inlier_rmse=0.000000e+00, and correspondence_set size of 159
Access transformation to get result.
Transformation after ICP is:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
0  points added
Apply Generalised ICP
RegistrationResult with fitness=8.153846e-01, inlier_rmse=7.203564e-02, and correspondence_set size of 159
Access transformation to get result.
Transformation after ICP is:
[[ 0.98988407  0.13901918 -0.02834055  0.51153116]
 [-0.13254688  0.9773867   0.16476213 -0.01602939]
 [ 0.05060478 -0.15933896  0.98592609 -0.16620102]
 [ 0.          0.          0.          1.        ]]
159  points added
Apply Generalised ICP
RegistrationResult with fitness=8.916667e-01, inlier_rmse=6.046268e-02, and correspondence_set size of 214
Access transformation to get result.
Transformation after ICP is:
[[ 0.99895114 -0.00919191 -0.04485679  0.8615367 ]
 [ 0.00705423  0.99884

array([[ 3.81278133, -0.70387304,  2.36399841],
       [ 3.64729309, -0.23136237,  1.77690804],
       [ 3.64106178, -0.25650048,  1.77481008],
       ...,
       [ 2.83879023, -0.33993886,  2.22968288],
       [ 2.83481644, -0.3309662 ,  2.22908991],
       [ 2.8307489 , -0.32203591,  2.22849325]])

In [51]:
def display_inlier_outlier(cloud, ind):
    inlier_cloud = cloud.select_by_index(ind)
    outlier_cloud = cloud.select_by_index(ind, invert=True)

    print("Showing outliers (red) and inliers (gray): ")
    outlier_cloud.paint_uniform_color([0, 1, 0])
    inlier_cloud.paint_uniform_color([0.8, 0.8, 0.8])
    o3d.visualization.draw_geometries([inlier_cloud, outlier_cloud],
                                      zoom=0.3412,
                                      front=[0.4257, -0.2125, -0.8795],
                                      lookat=[2.6172, 2.0475, 1.532],
                                      up=[-0.0694, -0.9768, 0.2024])

In [47]:
len(reg_points)

1804