In [2]:
import open3d as o3d
import numpy as np
import importlib
import matplotlib.pyplot as plt
import h5py
import functions.pc_matching
import functions.mat_to_py
import functions.viz
import functions.pc_registration
importlib.reload(functions.pc_matching)
importlib.reload(functions.mat_to_py)
importlib.reload(functions.viz)
importlib.reload(functions.pc_registration)
from functions.pc_matching import PCMatch
from functions.mat_to_py import PCNIData
from functions.viz import pc_viz, video_cv, pc2video
from functions.pc_registration import PointReg
import cv2 as cv
import argparse
import numpy as np
import sklearn as skl
from sklearn.cluster import KMeans

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [10]:
static_point = PCNIData('C:\\Users\\dasgu\\Documents\\GithubPercep\\sensordata\\JanuaryRecording',eg=0)
static_pc = static_point('pc')
pc_viz(static_pc[50])
np.save('reference_pc_sensorfusion.npy',static_pc[120])

In [3]:
match_points = PCMatch()
datapoints = PCNIData('C:\\Users\\dasgu\\Documents\\GithubPercep\\sensordata\\JanuaryRecording',eg=0)
images = datapoints('image')
lidar = datapoints('pc')

Start


In [6]:
match_points = PCMatch()
datapoints = PCNIData('C:\\Users\\dasgu\\Documents\\GithubPercep\\sensordata\\JanuaryRecording',eg=0)
images = datapoints('image')
lidar = datapoints('pc')

In [7]:
cv.imshow('PC',images[800])
cv.waitKey(-1)

-1

In [10]:
static_pc = np.load('reference_pc_sensorfusion.npy')
cluster = match_points(static_pc,lidar[400])

[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 3
point cloud has 3 clusters
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 


End


The other data with the dual chair system


In [2]:
static_point = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=1)
static_pc = static_point('pc')
pc_viz(static_pc[150])
np.save('reference_pc_new.npy',static_pc[120])

loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_1_pc.mat
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 


In [2]:
match_points = PCMatch()
datapoints = PCNIData('C:\\Users\\dasgu\\Documents\\GitHubPercep\\sensordata\\Jul22data',eg=6)
images = datapoints('image')
lidar = datapoints('pc')

loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\imgdata\2022-06-16-13-01-40_6_img.mat
loading  C:\Users\dasgu\Documents\GitHubPercep\sensordata\Jul22data\pcdata\2022-06-16-13-01-40_6_pc.mat


In [4]:
video_cv(images)

In [13]:
lidar[100].shape

(57600, 3)

In [9]:
static_pc = np.load('reference_pc_sensorfusion.npy')
cluster = match_points(static_pc,lidar[500])

[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 1
point cloud has 1 clusters


In [23]:
cluster1 = match_points(static_pc,cluster[0])

[Open3D DEBUG] Precompute neighbors.
[Open3D DEBUG] Done Precompute neighbors.
[Open3D DEBUG] Compute Clusters
[Open3D DEBUG] Done Compute Clusters: 1
point cloud has 1 clusters
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 


In [4]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(cluster[0])
o3d.visualization.draw_geometries([pcd])

Test Sensor Fusion

In [5]:
cluster_homo = []
for i in cluster[0]:
    cluster_homo.append(np.append(i,1))
print(len(cluster_homo[0]))
cluster_homo

4


[array([ 4.43898487, -0.43835461,  1.89050853,  1.        ]),
 array([ 4.44048834, -0.42285699,  1.89050853,  1.        ]),
 array([ 4.38619137, -0.65784538,  2.13777304,  1.        ]),
 array([ 4.38618422, -0.62656641,  2.13567495,  1.        ]),
 array([ 4.38354349, -0.7044608 ,  2.13987112,  1.        ]),
 array([ 4.38397074, -0.64187318,  2.13567495,  1.        ]),
 array([ 4.38384962, -0.6106258 ,  2.13357687,  1.        ]),
 array([ 4.38595438, -0.59531957,  2.13357687,  1.        ]),
 array([ 4.38350677, -0.57941145,  2.13147902,  1.        ]),
 array([ 4.381001  , -0.56352752,  2.12938094,  1.        ]),
 array([ 4.37489653, -0.67177433,  2.13357687,  1.        ]),
 array([ 4.37843752, -0.54766816,  2.12728286,  1.        ]),
 array([ 4.3758173 , -0.53183359,  2.12518477,  1.        ]),
 array([ 4.37314034, -0.51602411,  2.12308669,  1.        ]),
 array([ 4.37040567, -0.50023973,  2.12098861,  1.        ]),
 array([ 4.36927843, -0.46923187,  2.11889052,  1.        ]),
 array([

In [6]:
cv.imshow('PC',images[30])
cv.waitKey(-1)

-1

In [7]:
cam_lid_trans = np.load('transformation\\CC_proj_L(1).npy')
cluster_trans =  np.dot(cam_lid_trans,np.transpose(cluster_homo))
cluster_trans =  np.transpose(cluster_trans)
# cluster_trans = cluster_trans[:,:-1]
# print(len(cluster_trans))
for i in cluster_trans:
    i[0] = i[0]/i[2]
    i[1] = i[1]/i[2]
    i[0] = i[0]/3
    i[1] = i[1]/3
cluster_trans

array([[124.49772283, 230.34421192,   3.53981506],
       [124.46680707, 229.28928296,   3.54020622],
       [143.57077401, 242.8626969 ,   3.74735811],
       [143.46589191, 240.88932604,   3.7449945 ],
       [143.74423482, 245.82907605,   3.74886017],
       [143.52034973, 241.88033365,   3.74431203],
       [143.41901284, 239.90748848,   3.74190255],
       [143.36806467, 238.91692709,   3.74254084],
       [143.32472173, 237.93559366,   3.73940362],
       [143.28315235, 236.95451936,   3.73624289],
       [143.64042179, 243.87191655,   3.73913121],
       [143.24336037, 235.97370427,   3.73305904],
       [143.20531831, 234.99314042,   3.72985249],
       [143.16902966, 234.01282965,   3.72662322],
       [143.13452938, 233.03276016,   3.72337086],
       [143.06489471, 231.06402943,   3.7205558 ],
       [143.10180574, 232.05292503,   3.7200956 ],
       [143.0356689 , 230.08461813,   3.71723589],
       [160.26047468, 230.09157169,   3.82143615],
       [160.29810669, 231.01859

In [5]:
img = images[30]
import math as m
for i in cluster_trans:
    x = m.trunc(i[1])
    y = m.trunc(i[0])
    print([x,y])
    img[x][y] = [120,5,5]
    img[x-1][y+1] = [120,5,5]
    img[x-1][y-1] = [120,5,5]
    img[x+1][y+1] = [120,5,5]
    img[x+1][y-1] = [120,5,5]
    
cv.imshow('PC',images[30])
cv.waitKey(-1)

NameError: name 'cluster_trans' is not defined

End Sensor Fusion

In [66]:
cluster_homo = []
for i in cluster[0]:
    cluster_homo.append(np.append(i,1))
print(len(cluster_homo[0]))
cluster_homo

4


[array([1.62195587, 0.54873812, 1.76243389, 1.        ]),
 array([1.60315979, 0.5486235 , 1.74491131, 1.        ]),
 array([1.57764399, 0.5460518 , 1.72037947, 1.        ]),
 array([1.57236242, 0.55037743, 1.71687496, 1.        ]),
 array([1.56037545, 0.24106383, 1.96697223, 1.        ]),
 array([1.56171203, 0.26700592, 1.79587126, 1.        ]),
 array([1.56370783, 0.55348295, 1.70986593, 1.        ]),
 array([1.5584085 , 0.55773622, 1.70636129, 1.        ]),
 array([1.54777825, 0.56615239, 1.69935215, 1.        ]),
 array([1.54579258, 0.57155168, 1.69935215, 1.        ]),
 array([1.53842854, 0.58106929, 1.69584751, 1.        ]),
 array([1.53329921, 0.59447229, 1.69584751, 1.        ]),
 array([1.53650236, 0.72274989, 1.74841571, 1.        ]),
 array([1.52403402, 0.26604414, 1.75544441, 1.        ]),
 array([1.52698994, 0.6104961 , 1.69584751, 1.        ]),
 array([1.52484965, 0.61582255, 1.69584751, 1.        ]),
 array([1.52381063, 0.62781137, 1.69935215, 1.        ]),
 array([1.5191

In [71]:
cv.imshow('PC',images[1000])
cv.waitKey(-1)

-1

In [7]:
import functions.sensor_fusion
importlib.reload(functions.Sensor_fusion)
from functions.sensor_fusion import CamLidar
cameratolidar = CamLidar(camera_parameters)

NameError: name 'Sensor_fusion' is not defined

In [68]:
cam_lid_trans = np.load('transformation\\CC_proj_L(1).npy')
cam_lid_trans

array([[-1.89394783e+02,  6.61381157e+00,  1.14609829e+03,
        -9.92071735e-01],
       [ 2.20069662e+02, -7.26857477e+02,  5.50958574e+02,
         1.09028622e+02],
       [ 4.06488870e-01, -1.41949041e-02,  9.13545458e-01,
         2.12923562e-03]])

In [80]:
print(np.transpose(cluster_homo).shape)

(4, 454)


In [88]:
cluster_trans =  np.dot(cam_lid_trans,np.transpose(cluster_homo))
cluster_trans =  np.transpose(cluster_trans)
# cluster_trans = cluster_trans[:,:-1]
print(len(cluster_trans))

454


In [54]:
cluster_trans =  np.dot(np.linalg.inv(cam_lid_trans),np.transpose(cluster_homo))
cluster_trans =  np.transpose(cluster_trans)
cluster_trans = cluster_trans[:,:-1]
print(len(cluster_trans[0]))

3


In [89]:
for i in cluster_trans:
    i[0] = i[0]/i[2]
    i[1] = i[1]/i[2]
    i[0] = i[0]/3
    i[1] = i[1]/3
cluster_trans


array([[252.58967606, 152.86783761,   2.26371043],
       [252.79727003, 152.44180697,   2.24006399],
       [253.0289539 , 152.09654796,   2.20731766],
       ...,
       [343.11347577, 160.44418593,   2.48902526],
       [344.24725576, 158.15916693,   2.53647254],
       [343.76587855, 159.26396898,   2.4954348 ]])

In [97]:
img = images[1000]
print(len(img[0]))

640


In [98]:
import math as m
for i in cluster_trans:
    x = m.trunc(i[1])
    y = m.trunc(i[0])
    print([x,y])
    img[x][y] = [120,5,5]
    img[x-1][y+1] = [120,5,5]
    img[x-1][y-1] = [120,5,5]
    img[x+1][y+1] = [120,5,5]
    img[x+1][y-1] = [120,5,5]
    
cv.imshow('PC',images[1000])
cv.waitKey(-1)

[152, 252]
[152, 252]
[152, 253]
[151, 253]
[186, 268]
[182, 258]
[150, 253]
[150, 253]
[149, 253]
[148, 254]
[147, 254]
[145, 254]
[133, 258]
[182, 258]
[144, 255]
[143, 255]
[142, 255]
[184, 258]
[140, 256]
[138, 257]
[137, 257]
[136, 257]
[134, 258]
[182, 258]
[181, 258]
[181, 259]
[179, 259]
[178, 259]
[176, 259]
[175, 260]
[174, 260]
[186, 269]
[172, 260]
[171, 260]
[171, 260]
[170, 261]
[168, 261]
[167, 261]
[166, 261]
[165, 262]
[186, 269]
[188, 289]
[164, 262]
[163, 262]
[162, 262]
[161, 263]
[159, 263]
[187, 279]
[185, 269]
[158, 263]
[157, 264]
[156, 264]
[154, 264]
[134, 270]
[134, 270]
[185, 269]
[154, 264]
[152, 265]
[151, 265]
[149, 266]
[147, 278]
[146, 278]
[145, 278]
[138, 269]
[136, 270]
[135, 270]
[184, 269]
[148, 266]
[148, 266]
[147, 267]
[145, 267]
[143, 268]
[142, 268]
[141, 268]
[139, 269]
[142, 280]
[136, 270]
[187, 279]
[184, 269]
[150, 277]
[141, 280]
[140, 280]
[188, 290]
[186, 279]
[183, 269]
[172, 282]
[172, 282]
[170, 283]
[169, 283]
[168, 283]
[166, 284]

-1

In [85]:
cv.imwrite('trial.jpg', images[350])


True